name: 🐞 Bug Report
description: File a bug/issue
body:
  - type: markdown
    attributes:
      value: |
        # Octopus Community Library: Bug Report
        Thanks for taking the time to fill out a bug/issue report!
        
        If you are reporting a bug with a specific step template, we'd really appreciate it if you could send a PR with a fix for the bug.
        If you want to send a PR but you're not sure how to create a PR, see GitHub's excellent [Pull Request guides](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests). Note that sending your own PR will give you a faster resolution than the below options.

        If you can't send a PR thats not a problem! A member of the Octopus team will take a look at your issue and make sure that we get any fix merged as soon as we can. 

        **Please note:** It might take a bit longer to publish a bug fix depending on what step template(s) are affected and what the issue is as it could require some setup to replicate.
  - type: input
    id: step-template
    attributes:
      label: Step template
      description: Please tell us which step template(s) you are having issues with.
      placeholder: e.g., GCP Secret Manager - Retrieve Secrets
    validations:
      required: false
  - type: input
    id: step-template-version
    attributes:
      label: Step version
      description: Please tell us the version of the step template you are having issues with.
      placeholder: e.g., 1
    validations:
      required: false
  - type: input
    id: octopus-version
    attributes:
      label: Octopus version
      description: Please provide what version of Octopus you are currently running.
      placeholder: e.g., 2023.3.xxxx
    validations:
      required: false
  - type: textarea
    id: step-parameter-inputs
    attributes:
      label: Step template parameter inputs
      description: Please show us how you have configured your step template, to make it easier for us to replicate the issue.
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened
      description: What actually happened?
      placeholder: Tell us what is wrong
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction steps
      description: If there are specific steps that you took when you encountered the problem, please outline them here.  
      placeholder: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: more-information
    attributes:
      label: More Information
      description: Anything else that can help us solve the problem, logs, links, screenshots, suspicions, add them here. 
      placeholder: Tell us more
    validations:
      required: false

